backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "rooms"
    label: "ROOOMZ"
    folder: "src/pages/rooms"
    create: true
    description: "blah-blah-blah rooms"
    fields:
      - {
          name: "title",
          label: "TITLE",
          widget: "string",
          pattern:
            [".{10,}", "Must have at least 10 characters, hha-ha-ha-ha!"],
        }
      - { label: "OVERVIEW", name: "overview", widget: "text" }
      - { label: "PRICE", name: "price", widget: "string" }
      - { label: "Room Image", name: "roomimage", widget: "image" }
